# ElastiCache Redis for the Checkout service, with genuine primary/replica
# replication rather than a single node. Configuration confirmed against
# Checkout's actual source (RedisCheckoutRepository.ts) before writing
# this file - see docs/DECISIONS.md ADR-009.
#
# Replication is not a default-to-safe choice here, it is required: the
# application code opens two separate ioredis clients, one against the
# writer URL (used for set/remove) and one against the reader URL (used
# for get), with no visible fallback if the reader URL is empty. A
# single-node deployment would leave that code path untested against a
# real reader endpoint.
#
# Unlike Aurora (aurora.tf), ElastiCache has no equivalent to RDS's
# manage_master_user_password feature - there is no AWS-managed
# auto-generated auth token option. The auth token below is generated by
# Terraform itself via the random provider, which means it exists in
# Terraform state, a real, known tradeoff, not an oversight. This is the
# closest available equivalent given ElastiCache's actual feature set.

resource "aws_elasticache_subnet_group" "redis" {
  name       = "${var.project_name}-redis-subnet-group"
  subnet_ids = aws_subnet.private[*].id

  tags = {
    Name = "${var.project_name}-redis-subnet-group"
  }
}

resource "random_password" "redis_auth" {
  length  = 32
  special = false # ElastiCache AUTH tokens do not permit all special characters
}

resource "aws_elasticache_replication_group" "checkout" {
  replication_group_id = "${var.project_name}-checkout-redis"
  description           = "Redis for Checkout service session/cart state"

  engine         = "redis"
  node_type      = var.redis_node_type
  num_cache_clusters = var.redis_num_cache_clusters
  # Set explicitly rather than left to default. Without this, Terraform
  # cannot know the port at plan time (it's an AWS-side default it
  # wouldn't assign until apply), which breaks the connection-string
  # construction below - confirmed the hard way via a plan-time error.
  port = 6379

  # Required for the primary endpoint to remain valid across a failover,
  # and for the reader endpoint to exist at all with more than one node.
  automatic_failover_enabled = true
  multi_az_enabled           = true

  subnet_group_name = aws_elasticache_subnet_group.redis.name
  security_group_ids = [aws_security_group.redis.id]

  # Confirmed against Checkout's own ioredis client: rediss:// (TLS)
  # requires transit_encryption_enabled here to match. Getting this
  # mismatched with the URL scheme in ecs-checkout.tf would fail the
  # connection outright.
  transit_encryption_enabled = true
  at_rest_encryption_enabled = true
  auth_token                 = random_password.redis_auth.result

  tags = {
    Name = "${var.project_name}-checkout-redis"
  }
}

# Full connection strings (protocol + embedded auth token + endpoint),
# stored as Secrets Manager secrets rather than passed as plain
# environment variables, since ioredis takes the entire URL as a single
# value and that value now contains the AUTH token. Two separate secrets,
# one per endpoint, matching the two separate env vars Checkout actually
# reads (RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL and
# RETAIL_CHECKOUT_PERSISTENCE_REDIS_READER_URL).
resource "aws_secretsmanager_secret" "redis_writer_url" {
  name = "${var.project_name}-redis-writer-url"

  # Secrets Manager schedules a 30-day recovery window by default, even
  # after `tofu destroy`, and refuses to create a new secret with the
  # same name until that window elapses. This is a personal dev/test
  # project torn down between sessions; skipping the window avoids a
  # name collision on the very next apply. Same reasoning as ECR's
  # force_delete and Aurora's skip_final_snapshot elsewhere in this
  # project - a production version would not set this.
  recovery_window_in_days = 0

  tags = {
    Name = "${var.project_name}-redis-writer-url"
  }
}

resource "aws_secretsmanager_secret_version" "redis_writer_url" {
  secret_id = aws_secretsmanager_secret.redis_writer_url.id
  secret_string = "rediss://:${random_password.redis_auth.result}@${aws_elasticache_replication_group.checkout.primary_endpoint_address}:${aws_elasticache_replication_group.checkout.port}"
}

resource "aws_secretsmanager_secret" "redis_reader_url" {
  name = "${var.project_name}-redis-reader-url"

  # See redis_writer_url above for why this is intentionally 0 here.
  recovery_window_in_days = 0

  tags = {
    Name = "${var.project_name}-redis-reader-url"
  }
}

resource "aws_secretsmanager_secret_version" "redis_reader_url" {
  secret_id = aws_secretsmanager_secret.redis_reader_url.id
  secret_string = "rediss://:${random_password.redis_auth.result}@${aws_elasticache_replication_group.checkout.reader_endpoint_address}:${aws_elasticache_replication_group.checkout.port}"
}
